window.buttonsList = [
{currencySymbol: "د.إ",countryFlag: "🇦🇪",currencyName: "AED",currencyDescription: "United Arab Emirates Dirham",},
{currencySymbol: "A$",countryFlag: "🇦🇺",currencyName: "AUD",currencyDescription: "Australian Dollar",},
{currencySymbol: "Лв.",countryFlag: "🇧🇬",currencyName: "BGN",currencyDescription: "Bulgarian Lev",},
{currencySymbol: ". د",countryFlag: "🇧🇭",currencyName: "BHD",currencyDescription: "Bahraini Dinar",},
{currencySymbol: "C$",countryFlag: "🇨🇦",currencyName: "CAD",currencyDescription: "Canadian Dollar",},
{currencySymbol: "CHf",countryFlag: "🇨🇭",currencyName: "CHF",currencyDescription: "Swiss Franc",},
{currencySymbol: "¥",countryFlag: "🇨🇳",currencyName: "CNY",currencyDescription: "Chinese Yuan",},
{currencySymbol: "Kč",countryFlag: "🇨🇿",currencyName: "CZK",currencyDescription: "Czech Koruna",},
{currencySymbol: "Kr.",countryFlag: "🇩🇰",currencyName: "DKK",currencyDescription: "Danish Krone",},
{currencySymbol: "€",countryFlag: "🇪🇺",currencyName: "EUR",currencyDescription: "Euro",},
{currencySymbol: "£",countryFlag: "🇬🇧",currencyName: "GBP",currencyDescription: "British Pound",},
{currencySymbol: "HK$",countryFlag: "🇭🇰",currencyName: "HKD",currencyDescription: "Hong Kong Dollar",},
{currencySymbol: "Ft",countryFlag: "🇭🇺",currencyName: "HUF",currencyDescription: "Hungarian Forint",},
{currencySymbol: "₪",countryFlag: "🇮🇱",currencyName: "ILS",currencyDescription: "Israeli New Sheqel",},
{currencySymbol: "¥",countryFlag: "🇯🇵",currencyName: "JPY",currencyDescription: "Japanese Yen",},
{currencySymbol: "/-",countryFlag: "🇰🇪",currencyName: "KES",currencyDescription: "Kenyan Shilling",},
{currencySymbol: "ك",countryFlag: "🇰🇼",currencyName: "KWD",currencyDescription: "Kuwaiti Dinar",},
{currencySymbol: "Mex$",countryFlag: "🇲🇽",currencyName: "MXN",currencyDescription: "Mexican Peso",},
{currencySymbol: "kr",countryFlag: "🇳🇴",currencyName: "NOK",currencyDescription: "Norwegian Krone",},
{currencySymbol: "$",countryFlag: "🇳🇿",currencyName: "NZD",currencyDescription: "New Zealand Dollar",},
{currencySymbol: "ر.ع",countryFlag: "🇴🇲",currencyName: "OMR",currencyDescription: "Omani Rial",},
{currencySymbol: "zł",countryFlag: "🇵🇱",currencyName: "PLN",currencyDescription: "Polish Zloty",},
{currencySymbol: "ر.ق",countryFlag: "🇶🇦",currencyName: "QAR",currencyDescription: "Qatari Rial",},
{currencySymbol: "lei",countryFlag: "🇷🇴",currencyName: "RON",currencyDescription: "Romanian New Leu",},
{currencySymbol: "ر.س",countryFlag: "🇸🇦",currencyName: "SAR",currencyDescription: "Saudi Riyal",},
{currencySymbol: "kr",countryFlag: "🇸🇪",currencyName: "SEK",currencyDescription: "Swedish Krona",},
{currencySymbol: "S$",countryFlag: "🇸🇬",currencyName: "SGD",currencyDescription: "Singapore Dollar",},
{currencySymbol: "฿",countryFlag: "🇹🇭",currencyName: "THB",currencyDescription: "Thai Baht",},
{currencySymbol: "₺",countryFlag: "🇹🇷",currencyName: "TRY",currencyDescription: "Turkish Lira",},
{currencySymbol: "USh",countryFlag: "🇺🇬",currencyName: "UGX",currencyDescription: "Ugandan Shilling",},
{currencySymbol: "$",countryFlag: "🇺🇸",currencyName: "USD",currencyDescription: "United States dollar",},
{currencySymbol: "R",countryFlag: "🇿🇦",currencyName: "ZAR",currencyDescription: "South African Rand",},
{currencySymbol: "¥",countryFlag: "🇨🇳",currencyName: "CNH",currencyDescription: "The offshore RMB",},
{currencySymbol: "؋",countryFlag: "🇦🇫",currencyName: "AFN",currencyDescription: "Afghan Afghani",},
{currencySymbol: "Lek",countryFlag: "🇦🇱",currencyName: "ALL",currencyDescription: "Albanian Lek",},
{currencySymbol: "DA",countryFlag: "🇩🇿",currencyName: "DZD",currencyDescription: "Algerian Dinar",},
{currencySymbol: "Kz",countryFlag: "🇦🇴",currencyName: "AOA",currencyDescription: "Angolan Kwanza",},
{currencySymbol: "$",countryFlag: "🇧🇶",currencyName: "XCD",currencyDescription: "East Caribbean Dollar",},
{currencySymbol: "$",countryFlag: "🇦🇷",currencyName: "ARS",currencyDescription: "Argentine Peso",},
{currencySymbol: "֏",countryFlag: "🇦🇲",currencyName: "AMD",currencyDescription: "Armenian Dram",},
{currencySymbol: "₼",countryFlag: "🇦🇿",currencyName: "AZN",currencyDescription: "Azerbaijani Manat",},
{currencySymbol: "$",countryFlag: "🇧🇸",currencyName: "BSD",currencyDescription: "Bahamian Dollar",},
{currencySymbol: "Tk",countryFlag: "🇧🇩",currencyName: "BDT",currencyDescription: "Bangladeshi Taka",},
{currencySymbol: "$",countryFlag: "🇧🇧",currencyName: "BBD",currencyDescription: "Barbadian Dollar",},
{currencySymbol: "Br",countryFlag: "🇧🇾",currencyName: "BYN",currencyDescription: "Belarusian Ruble",},
{currencySymbol: "BZ$",countryFlag: "🇧🇿",currencyName: "BZD",currencyDescription: "Belize Dollar",},
{currencySymbol: "Franc",countryFlag: "🇨🇫",currencyName: "XOF",currencyDescription: "West African CFA Franc",},
{currencySymbol: "$",countryFlag: "🇧🇲",currencyName: "BMD",currencyDescription: "Bermudan Dollar",},
{currencySymbol: "$b",countryFlag: "🇧🇴",currencyName: "BOB",currencyDescription: "Bolivian Boliviano",},
{currencySymbol: "KM",countryFlag: "🇧🇦",currencyName: "BAM",currencyDescription: "Bosnia-Herzegovina Convertible Mark",},
{currencySymbol: "P",countryFlag: "🇧🇼",currencyName: "BWP",currencyDescription: "Botswanan Pula",},
{currencySymbol: "R$",countryFlag: "🇧🇷",currencyName: "BRL",currencyDescription: "Brazilian Real",},
{currencySymbol: "$",countryFlag: "🇧🇳",currencyName: "BND",currencyDescription: "Brunei Dollar",},
{currencySymbol: "Franc",countryFlag: "🇧🇮",currencyName: "BIF",currencyDescription: "Burundian Franc",},
{currencySymbol: "៛",countryFlag: "🇰🇭",currencyName: "KHR",currencyDescription: "Cambodian Riel",},
{currencySymbol: "CFA Franc BEAC",countryFlag: "🇨🇫",currencyName: "XAF",currencyDescription: "Central African CFA Franc",},
{currencySymbol: "$",countryFlag: "🇨🇻",currencyName: "CVE",currencyDescription: "Cape Verdean Escudo",},
{currencySymbol: "Dinar",countryFlag: "🇰🇾",currencyName: "KYD",currencyDescription: "Cayman Islands Dollar",},
{currencySymbol: "$",countryFlag: "🇨🇱",currencyName: "CLP",currencyDescription: "Chilean Peso",},
{currencySymbol: "$",countryFlag: "🇨🇴",currencyName: "COP",currencyDescription: "Colombian Peso",},
{currencySymbol: "₡",countryFlag: "🇨🇷",currencyName: "CRC",currencyDescription: "Costa Rican Colón",},
{currencySymbol: "kn",countryFlag: "🇭🇷",currencyName: "HRK",currencyDescription: "Croatian Kuna",},
{currencySymbol: "Franc",countryFlag: "🇩🇯",currencyName: "DJF",currencyDescription: "Djiboutian Franc",},
{currencySymbol: "RD$",countryFlag: "🇩🇴",currencyName: "DOP",currencyDescription: "Dominican Peso",},
{currencySymbol: "£",countryFlag: "🇪🇬",currencyName: "EGP",currencyDescription: "Egyptian Pound",},
{currencySymbol: "Nkf",countryFlag: "🇪🇷",currencyName: "ERN",currencyDescription: "Eritrean Nakfa",},
{currencySymbol: "Br",countryFlag: "🇪🇹",currencyName: "ETB",currencyDescription: "Ethiopian Birr",},
{currencySymbol: "$",countryFlag: "🇫🇯",currencyName: "FJD",currencyDescription: "Fijian Dollar",},
{currencySymbol: "Dalasi",countryFlag: "🇬🇲",currencyName: "GMD",currencyDescription: "Gambian Dalasi",},
{currencySymbol: "Lari",countryFlag: "🇬🇪",currencyName: "GEL",currencyDescription: "Georgian Lari",},
{currencySymbol: "GH¢",countryFlag: "🇬🇭",currencyName: "GHS",currencyDescription: "Ghanaian Cedi",},
{currencySymbol: "Q",countryFlag: "🇬🇹",currencyName: "GTQ",currencyDescription: "Guatemalan Quetzal",},
{currencySymbol: "Franc",countryFlag: "🇬🇳",currencyName: "GNF",currencyDescription: "Guinean Franc",},
{currencySymbol: "$",countryFlag: "🇬🇾",currencyName: "GYD",currencyDescription: "Guyanaese Dollar",},
{currencySymbol: "G",countryFlag: "🇭🇹",currencyName: "HTG",currencyDescription: "Haitian Gourde",},
{currencySymbol: "L",countryFlag: "🇭🇳",currencyName: "HNL",currencyDescription: "Honduran Lempira",},
{currencySymbol: "$",countryFlag: "🇮🇸",currencyName: "ISK",currencyDescription: "Icelandic Króna",},
{currencySymbol: "₹",countryFlag: "🇮🇳",currencyName: "INR",currencyDescription: "Indian Rupee",},
{currencySymbol: "₹",countryFlag: "🇮🇳",currencyName: "IDR",currencyDescription: "Indonesian Rupiah",},
{currencySymbol: "د.ع",countryFlag: "🇮🇶",currencyName: "IQD",currencyDescription: "Iraqi Dinar",},
{currencySymbol: "J$",countryFlag: "🇯🇲",currencyName: "JMD",currencyDescription: "Jamaican Dollar",},
{currencySymbol: "S",countryFlag: "🇯🇴",currencyName: "JOD",currencyDescription: "Jordanian Dinar",},
{currencySymbol: "₸",countryFlag: "🇰🇿",currencyName: "KZT",currencyDescription: "Kazakhstani Tenge",},
{currencySymbol: "лв",countryFlag: "🇰🇬",currencyName: "KGS",currencyDescription: "Kyrgystani Som",},
{currencySymbol: "₭",countryFlag: "🇱🇦",currencyName: "LAK",currencyDescription: "Laotian Kip",},
{currencySymbol: "Loti",countryFlag: "🇱🇸",currencyName: "LSL",currencyDescription: "Lesotho Loti",},
{currencySymbol: "MOP$",countryFlag: "🇲🇴",currencyName: "MOP",currencyDescription: "Macanese Pataca",},
{currencySymbol: "Ar",countryFlag: "🇲🇬",currencyName: "MGA",currencyDescription: "Malagasy Ariary",},
{currencySymbol: "MK",countryFlag: "🇲🇼",currencyName: "MWK",currencyDescription: "Malawian Kwacha",},
{currencySymbol: "RM",countryFlag: "🇲🇾",currencyName: "MYR",currencyDescription: "Malaysian Ringgit",},
{currencySymbol: "Rufiyaa",countryFlag: "🇲🇻",currencyName: "MVR",currencyDescription: "Maldivian Rufiyaa",},
{currencySymbol: "₨",countryFlag: "🇲🇺",currencyName: "MUR",currencyDescription: "Mauritian Rupee",},
{currencySymbol: "₮",countryFlag: "🇲🇳",currencyName: "MNT",currencyDescription: "Mongolian Tugrik",},
{currencySymbol: "Dirham",countryFlag: "🇲🇦",currencyName: "MAD",currencyDescription: "Moroccan Dirham",},
{currencySymbol: "MT",countryFlag: "🇲🇿",currencyName: "MZN",currencyDescription: "Mozambican Metical",},
{currencySymbol: "K",countryFlag: "🇲🇲",currencyName: "MMK",currencyDescription: "Myanmar Kyat",},
{currencySymbol: "$",countryFlag: "🇳🇦",currencyName: "NAD",currencyDescription: "Namibian Dollar",},
{currencySymbol: "₨",countryFlag: "🇳🇵",currencyName: "NPR",currencyDescription: "Nepalese Rupee",},
{currencySymbol: "ƒ",countryFlag: "🇳🇱",currencyName: "ANG",currencyDescription: "Netherlands Antillean Guilder",},
{currencySymbol: "C$",countryFlag: "🇳🇮",currencyName: "NIO",currencyDescription: "Nicaraguan Córdoba",},
{currencySymbol: "₦",countryFlag: "🇳🇬",currencyName: "NGN",currencyDescription: "Nigerian Naira",},
{currencySymbol: "Rs",countryFlag: "🇵🇰",currencyName: "PKR",currencyDescription: "Pakistani Rupee",},
{currencySymbol: "K",countryFlag: "🇵🇬",currencyName: "PGK",currencyDescription: "Papua New Guinean Kina",},
{currencySymbol: "Gs",countryFlag: "🇵🇾",currencyName: "PYG",currencyDescription: "Paraguayan Guarani",},
{currencySymbol: "S/.",countryFlag: "🇵🇪",currencyName: "PEN",currencyDescription: "Peruvian Sol",},
{currencySymbol: "₱",countryFlag: "🇵🇭",currencyName: "PHP",currencyDescription: "Philippine Piso",},
{currencySymbol: "Franc",countryFlag: "🇷🇼",currencyName: "RWF",currencyDescription: "Rwandan Franc",},
{currencySymbol: "$",countryFlag: "🇼🇸",currencyName: "WST",currencyDescription: "Samoan Tala",},
{currencySymbol: "Db",countryFlag: "🇸🇹",currencyName: "STN",currencyDescription: "São Tomé & Príncipe Dobra",},
{currencySymbol: "РСД",countryFlag: "🇷🇸",currencyName: "RSD",currencyDescription: "Serbian Dinar",},
{currencySymbol: "₨",countryFlag: "🇸🇨",currencyName: "SCR",currencyDescription: "Seychellois Rupee",},
{currencySymbol: "Le",countryFlag: "🇸🇱",currencyName: "SLL",currencyDescription: "Sierra Leonean Leone",},
{currencySymbol: "$",countryFlag: "🇸🇧",currencyName: "SBD",currencyDescription: "Solomon Islands Dollar",},
{currencySymbol: "₩",countryFlag: "🇰🇷",currencyName: "KRW",currencyDescription: "South Korean Won",},
{currencySymbol: "₨",countryFlag: "🇱🇰",currencyName: "LKR",currencyDescription: "Sri Lankan Rupee",},
{currencySymbol: "$",countryFlag: "🇸🇷",currencyName: "SRD",currencyDescription: "Surinamese Dollar",},
{currencySymbol: "Lilangeni",countryFlag: "🇸🇿",currencyName: "SZL",currencyDescription: "Swazi Lilangeni",},
{currencySymbol: "Franc",countryFlag: "🇫🇷",currencyName: "XPF",currencyDescription: "CFP Franc",},
{currencySymbol: "NT$",countryFlag: "🇹🇼",currencyName: "TWD",currencyDescription: "New Taiwan Dollar",},
{currencySymbol: "Shilling",countryFlag: "🇹🇿",currencyName: "TZS",currencyDescription: "Tanzanian Shilling",},
{currencySymbol: "T$",countryFlag: "🇹🇴",currencyName: "TOP",currencyDescription: "Tongan Paʻanga",},
{currencySymbol: "TT$",countryFlag: "🇹🇹",currencyName: "TTD",currencyDescription: "Trinidad & Tobago Dollar",},
{currencySymbol: "Dinar",countryFlag: "🇹🇳",currencyName: "TND",currencyDescription: "Tunisian Dinar",},
{currencySymbol: "₴",countryFlag: "🇺🇦",currencyName: "UAH",currencyDescription: "Ukrainian Hryvnia",},
{currencySymbol: "VT",countryFlag: "🇻🇺",currencyName: "VUV",currencyDescription: "Vanuatu Vatu",},
{currencySymbol: "₫",countryFlag: "🇻🇳",currencyName: "VND",currencyDescription: "Vietnamese Dong",},
{currencySymbol: "Lek",countryFlag: "🇿🇲",currencyName: "ZMW",currencyDescription: "Zambian Kwacha",},
];

