window.buttonsListSaving = [
    {currencySymbol: '$', countryFlag: '🇺🇸', currencyName: 'USD', currencyDescription: 'United States dollar'},
    {currencySymbol: '€', countryFlag: '🇪🇺', currencyName: 'EUR', currencyDescription: 'Euro'},
    {currencySymbol: 'د.إ', countryFlag: '🇦🇪', currencyName: 'AED', currencyDescription: 'United Arab Emirates Dirham'},
    {currencySymbol: 'A$', countryFlag: '🇦🇺', currencyName: 'AUD', currencyDescription: 'Australian Dollar'},
    {currencySymbol: 'Лв.', countryFlag: '🇧🇬', currencyName: 'BGN', currencyDescription: 'Bulgarian Lev'},
    {currencySymbol: 'C$', countryFlag: '🇨🇦', currencyName: 'CAD', currencyDescription: 'Canadian Dollar'},
    {currencySymbol: 'CHf', countryFlag: '🇨🇭', currencyName: 'CHF', currencyDescription: 'Swiss Franc'},
    {currencySymbol: '¥', countryFlag: '🇨🇳', currencyName: 'CNY', currencyDescription: 'Chinese Yuan'},
    {currencySymbol: 'Kč', countryFlag: '🇨🇿', currencyName: 'CZK', currencyDescription: 'Czech Koruna'},
    {currencySymbol: 'Kr.', countryFlag: '🇩🇰', currencyName: 'DKK', currencyDescription: 'Danish Krone'},
    {currencySymbol: '£', countryFlag: '🇬🇧', currencyName: 'GBP', currencyDescription: 'British Pound'},
    {currencySymbol: 'HK$', countryFlag: '🇭🇰', currencyName: 'HKD', currencyDescription: 'Hong Kong Dollar'},
    {currencySymbol: 'Ft', countryFlag: '🇭🇺', currencyName: 'HUF', currencyDescription: 'Hungarian Forint'},
    {currencySymbol: 'Rp', countryFlag: '🇮🇩', currencyName: 'IDR', currencyDescription: 'Indonesian Rupiah'},
    {currencySymbol: '₪', countryFlag: '🇮🇱', currencyName: 'ILS', currencyDescription: 'Israeli New Sheqel'},
    {currencySymbol: '¥', countryFlag: '🇯🇵', currencyName: 'JPY', currencyDescription: 'Japanese Yen'},
    {currencySymbol: '/-', countryFlag: '🇰🇪', currencyName: 'KES', currencyDescription: 'Kenyan Shilling'},
    {currencySymbol: 'Mex$', countryFlag: '🇲🇽', currencyName: 'MXN', currencyDescription: 'Mexican Peso'},
    {currencySymbol: 'RM', countryFlag: '🇲🇾', currencyName: 'MYR', currencyDescription: 'Malaysian Ringgit'},
    {currencySymbol: 'kr', countryFlag: '🇳🇴', currencyName: 'NOK', currencyDescription: 'Norwegian Krone'},
    {currencySymbol: '$', countryFlag: '🇳🇿', currencyName: 'NZD', currencyDescription: 'New Zealand Dollar'},
    {currencySymbol: '₱', countryFlag: '🇵🇭', currencyName: 'PHP', currencyDescription: 'Philippine Peso'},
    {currencySymbol: 'zł', countryFlag: '🇵🇱', currencyName: 'PLN', currencyDescription: 'Polish Zloty'},
    {currencySymbol: 'lei', countryFlag: '🇷🇴', currencyName: 'RON', currencyDescription: 'Romanian New Leu'},
    {currencySymbol: 'ر.س', countryFlag: '🇸🇦', currencyName: 'SAR', currencyDescription: 'Saudi Riyal'},
    {currencySymbol: 'kr', countryFlag: '🇸🇪', currencyName: 'SEK', currencyDescription: 'Swedish Krona'},
    {currencySymbol: 'S$', countryFlag: '🇸🇬', currencyName: 'SGD', currencyDescription: 'Singapore Dollar'},
    {currencySymbol: '฿', countryFlag: '🇹🇭', currencyName: 'THB', currencyDescription: 'Thai Baht'},
    {currencySymbol: '₺', countryFlag: '🇹🇷', currencyName: 'TRY', currencyDescription: 'Turkish Lira'},
    {currencySymbol: 'USh', countryFlag: '🇺🇬', currencyName: 'UGX', currencyDescription: 'Ugandan Shilling'},
    {currencySymbol: 'R', countryFlag: '🇿🇦', currencyName: 'ZAR', currencyDescription: 'South African Rand'},
    {currencySymbol: "$",countryFlag: "🇦🇷",currencyName: "ARS",currencyDescription: "Argentine Peso",},
    {currencySymbol: "Tk",countryFlag: "🇧🇩",currencyName: "BDT",currencyDescription: "Bangladeshi Taka",},
    {currencySymbol: "R$",countryFlag: "🇧🇷",currencyName: "BRL",currencyDescription: "Brazilian Real",},
    {currencySymbol: "P",countryFlag: "🇧🇼",currencyName: "BWP",currencyDescription: "Botswanan Pula",},
    {currencySymbol: "$",countryFlag: "🇨🇱",currencyName: "CLP",currencyDescription: "Chilean Peso",},
    {currencySymbol: "$",countryFlag: "🇨🇴",currencyName: "COP",currencyDescription: "Colombian Peso",},
    {currencySymbol: "₡",countryFlag: "🇨🇷",currencyName: "CRC",currencyDescription: "Costa Rican Colón",},
    {currencySymbol: "£",countryFlag: "🇪🇬",currencyName: "EGP",currencyDescription: "Egyptian Pound",},
    {currencySymbol: "$",countryFlag: "🇫🇯",currencyName: "FJD",currencyDescription: "Fijian Dollar",},
    {currencySymbol: "Lari",countryFlag: "🇬🇪",currencyName: "GEL",currencyDescription: "Georgian Lari",},
    {currencySymbol: "GH¢",countryFlag: "🇬🇭",currencyName: "GHS",currencyDescription: "Ghanaian Cedi",},
    {currencySymbol: "Q",countryFlag: "🇬🇹",currencyName: "GTQ",currencyDescription: "Guatemalan Quetzal",},
    {currencySymbol: "₹",countryFlag: "🇮🇳",currencyName: "INR",currencyDescription: "Indian Rupee",},
    {currencySymbol: "₩",countryFlag: "🇰🇷",currencyName: "KRW",currencyDescription: "South Korean Won",},
    {currencySymbol: "₨",countryFlag: "🇱🇰",currencyName: "LKR",currencyDescription: "Sri Lankan Rupee",},
    {currencySymbol: "Dirham",countryFlag: "🇲🇦",currencyName: "MAD",currencyDescription: "Moroccan Dirham",},
    {currencySymbol: "₦",countryFlag: "🇳🇬",currencyName: "NGN",currencyDescription: "Nigerian Naira",},
    {currencySymbol: "₨",countryFlag: "🇳🇵",currencyName: "NPR",currencyDescription: "Nepalese Rupee",},
    {currencySymbol: "Rs",countryFlag: "🇵🇰",currencyName: "PKR",currencyDescription: "Pakistani Rupee",},
    {currencySymbol: "Shilling",countryFlag: "🇹🇿",currencyName: "TZS",currencyDescription: "Tanzanian Shilling",},
    {currencySymbol: "₴",countryFlag: "🇺🇦",currencyName: "UAH",currencyDescription: "Ukrainian Hryvnia",},
    {currencySymbol: "₫",countryFlag: "🇻🇳",currencyName: "VND",currencyDescription: "Vietnamese Dong",},
    {currencySymbol: "Franc",countryFlag: "🇨🇫",currencyName: "XOF",currencyDescription: "West African CFA Franc",},
    {currencySymbol: "Lek",countryFlag: "🇿🇲",currencyName: "ZMW",currencyDescription: "Zambian Kwacha",},
];
